import { Footer } from '@/src/components/Footer/Footer';
import { Header } from '@/src/components/Header/Header';
import { Providers } from '@/src/shared/Providers';
import type { Metadata } from 'next';
import './globals.css';


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
                                     children,
                                   }: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
    <body >
    <Providers>
      <Header />
      <div id='content'>
        {children}
      </div>
      <Footer />
    </Providers>
    </body>
    </html>
  );
}
